NEW Adds options parsing and help message to all commands

diff --git a/i3h/i3h-current-workspace b/i3h/i3h-current-workspace
--- a/i3h/i3h-current-workspace
+++ b/i3h/i3h-current-workspace
@@ -1,2 +1,30 @@
 #!/bin/sh
+USAGE="$0"'
+Returns the name of the current workspace.'
+
+# Parsing
+SHORT="h"
+LONG="help"
+OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
+! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
+eval set -- "$OPTS"
+
+while [[ "$#" -gt 0 ]]
+do
+    case "$1" in
+        -h|--help)
+            echo "$USAGE"
+            exit 1
+            ;;
+        --)
+            shift
+            ;;
+        *)
+            { echo "ERROR: Unexpected parameter" ; echo "$USAGE" ; } 1>&2
+            exit 1
+            ;;
+    esac
+done
+
+# Script
 i3-msg -t get_workspaces | jq -r '.[] | select(.focused==true).name' | tr -d '\n'
diff --git a/i3h/i3h-focus-mark b/i3h/i3h-focus-mark
--- a/i3h/i3h-focus-mark
+++ b/i3h/i3h-focus-mark
@@ -1,6 +1,33 @@
 #!/bin/bash
-# Focus the window with a specific mark.
-# Get's input from the first argument if preset, else from stdin.
+USAGE="$0"' [MARK]
+Marks the focused windows with MARK. 
+If no mark is given, reads from stdin.'
 
-[ -z "$1" ] && MARK="$(cat)" || MARK="$1"
+# Parsing
+SHORT="h"
+LONG="help"
+OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
+! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
+eval set -- "$OPTS"
+
+while [[ "$#" -gt 0 ]]
+do
+    case "$1" in
+        -h|--help)
+            echo "$USAGE"
+            exit 1
+            ;;
+        --)
+            # Leave it for later usage
+            shift
+            break
+            ;;
+        *)
+            { echo "ERROR: Unexpected parameter" ; echo "$USAGE" ; } 1>&2
+            exit 1
+            ;;
+    esac
+done
+
+[ -z "$@" ] && MARK="$(cat)" || MARK="$@"
 i3-msg '[con_mark="^'"$MARK"'$"] focus'
diff --git a/i3h/i3h-get-marks b/i3h/i3h-get-marks
--- a/i3h/i3h-get-marks
+++ b/i3h/i3h-get-marks
@@ -1,3 +1,30 @@
 #!/bin/bash
-# Returns all i3 marks, separated by newlines
+USAGE="$0"'
+Returns all i3 marks, separated by newlines.'
+
+# Parsing
+SHORT="h"
+LONG="help"
+OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
+! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
+eval set -- "$OPTS"
+
+while [[ "$#" -gt 0 ]]
+do
+    case "$1" in
+        -h|--help)
+            echo "$USAGE"
+            exit 1
+            ;;
+        --)
+            shift
+            ;;
+        *)
+            { echo "ERROR: Unexpected parameter" ; echo "$USAGE" ; } 1>&2
+            exit 1
+            ;;
+    esac
+done
+
+# Script
 i3-msg -t get_marks | jq -rM '.[]'
diff --git a/i3h/i3h-go-to-workspace b/i3h/i3h-go-to-workspace
--- a/i3h/i3h-go-to-workspace
+++ b/i3h/i3h-go-to-workspace
@@ -2,9 +2,36 @@
 USAGE="$0"' workspace-name
 Go to workspace name, if not there already.'
 
-WORKSPACE_NAME="$1"
-CURRENT_WORKSPACE="$(i3h-current-workspace)"
+# Parsing
+SHORT="h"
+LONG="help"
+OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
+! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
+eval set -- "$OPTS"
 
+while [[ "$#" -gt 0 ]]
+do
+    case "$1" in
+        -h|--help)
+            echo "$USAGE"
+            exit 1
+            ;;
+        --)
+            shift
+            WORKSPACE_NAME="$@"
+            break
+            ;;
+        *)
+            { echo "ERROR: Unexpected parameter" ; echo "$USAGE" ; } 1>&2
+            exit 1
+            ;;
+    esac
+done
+
+[ -z "$WORKSPACE_NAME" ] && { echo "ERROR: Missing workspace" ; echo "$USAGE" ; } 1>&2 && exit 1
+
+# Script
+CURRENT_WORKSPACE="$(i3h-current-workspace)"
 if ! [ "$WORKSPACE_NAME" = "$CURRENT_WORKSPACE" ]
 then
     i3-msg "workspace $WORKSPACE_NAME"
diff --git a/i3h/i3h-mark-window b/i3h/i3h-mark-window
--- a/i3h/i3h-mark-window
+++ b/i3h/i3h-mark-window
@@ -1,8 +1,35 @@
 #!/bin/bash -e
-# Marks the current i3 window with a user-prompted input.
-# Reads from stdin unless an argument is parsed, in which case uses it.
+USAGE="$0"' [MARK]
+Marks the current i3 window with a user-prompted input.
+Reads from stdin unless an argument is parsed, in which case uses it.'
 
+# Parsing
+SHORT="h"
+LONG="help"
+OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
+! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
+eval set -- "$OPTS"
+
+while [[ "$#" -gt 0 ]]
+do
+    case "$1" in
+        -h|--help)
+            echo "$USAGE"
+            exit 1
+            ;;
+        --)
+            shift
+            MARK="$@"
+            break
+            ;;
+        *)
+            { echo "ERROR: Unexpected parameter" ; echo "$USAGE" ; } 1>&2
+            exit 1
+            ;;
+    esac
+done
+
+# Script
 CURRENT_WINDOW_ID="$(i3h-focused-window | jq -rM '.window')"
-
-[ ! -z "$1" ] && MARK="$1" || MARK="$(cat)"
+[ -z "$MARK" ] && MARK="$(cat)"
 i3-msg "[id=$CURRENT_WINDOW_ID] mark $MARK"
diff --git a/i3h/i3h-move-workspaces-to-output b/i3h/i3h-move-workspaces-to-output
--- a/i3h/i3h-move-workspaces-to-output
+++ b/i3h/i3h-move-workspaces-to-output
@@ -1,18 +1,38 @@
 #!/bin/bash -e
-
-USAGE="\
-USAGE:
-  my-i3-move-workspaces-to-output <min_workspace_number> <output>
-DESCRIPTION:
-  Move all workspaces higher or equal than <min_workspace_number> to a specific <output>.
+USAGE="$0 min_workspace_number output
+Move all workspaces higher or equal than <min_workspace_number> to a specific <output>.
 EXAMPLE:
-  my-i3-move-workspaces-to-output 4 DP-1
-"
+  my-i3-move-workspaces-to-output 4 DP-1"
 
-[ ! "$#" = "2" ] && echo "$USAGE" 1>&2 && exit 1
+# Parsing
+SHORT="h"
+LONG="help"
+OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
+! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
+eval set -- "$OPTS"
 
-MIN_WORKSPACE="$1"
-TARGET_OUTPUT="$2"
+while [[ "$#" -gt 0 ]]
+do
+    case "$1" in
+        -h|--help)
+            echo "$USAGE"
+            exit 1
+            ;;
+        --)
+            MIN_WORKSPACE="$2"
+            TARGET_OUTPUT="$3"
+            break
+            ;;
+        *)
+            { echo "ERROR: Unexpected parameter" ; echo "$USAGE" ; } 1>&2
+            exit 1
+            ;;
+    esac
+done
+
+# Script
+[ -z $MIN_WORKSPACE ] && { echo "ERROR: Missing min_workspace" ; echo "$USAGE" ; } 1>&2 && exit 1
+[ -z $TARGET_OUTPUT ] && { echo "ERROR: Missing output" ; echo "$USAGE" ; } 1>&2 && exit 1
 WORKSPACES="$(i3-msg -t get_workspaces | jq '.[].num')"
 
 while read i
diff --git a/i3h/i3h-set-common-phrase-profile b/i3h/i3h-set-common-phrase-profile
--- a/i3h/i3h-set-common-phrase-profile
+++ b/i3h/i3h-set-common-phrase-profile
@@ -4,16 +4,35 @@ Sets a profile for i3h-common-phrases.
 The profile must be a file in `~/.config/i3h/common-phrases-profiles/<name>.json`.
 We simply creates a simbolic link to it, from `~/.config/i3h/common-phrases.json`.'
 
-# Usage
-if ! [ "$#" = "1" ]
-then
-    echo "ERROR: Exactly one argument is expected" 1>&2
-    echo "$USAGE" 1>&2
-    exit 1
-fi
+# Parsing
+SHORT="h"
+LONG="help"
+OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
+! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
+eval set -- "$OPTS"
+
+while [[ "$#" -gt 0 ]]
+do
+    case "$1" in
+        -h|--help)
+            echo "$USAGE"
+            exit 1
+            ;;
+        --)
+            shift
+            PROFILE="$@"
+            break
+            ;;
+        *)
+            { echo "ERROR: Unexpected parameter" ; echo "$USAGE" ; } 1>&2
+            exit 1
+            ;;
+    esac
+done
 
 # Parsing
-PROFILE_FILE=~/.config/i3h/common-phrases-profiles/"${1}.json"
+[ -z "$PROFILE" ] && { echo "ERROR: Missing PROFILE" ; echo "$USAGE" ; } 1>&2 && exit 1
+PROFILE_FILE=~/.config/i3h/common-phrases-profiles/"${PROFILE}.json"
 CONFIG_FILE=~/.config/i3h/common-phrases.json
 
 # Checks
diff --git a/i3h/i3h-toggle-border b/i3h/i3h-toggle-border
--- a/i3h/i3h-toggle-border
+++ b/i3h/i3h-toggle-border
@@ -1,5 +1,31 @@
 #!/bin/bash
-# Toggles border between normal and none
-CURRENT_BRODER="$(i3h-focused-window | jq -rM '.border')"
+USAGE="$0"'
+Returns all i3 marks, separated by newlines.'
 
+# Parsing
+SHORT="h"
+LONG="help"
+OPTS="$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")"
+! [ "$?" = 0 ] && echo "$USAGE" 1>&2 && exit 1
+eval set -- "$OPTS"
+
+while [[ "$#" -gt 0 ]]
+do
+    case "$1" in
+        -h|--help)
+            echo "$USAGE"
+            exit 1
+            ;;
+        --)
+            shift
+            ;;
+        *)
+            { echo "ERROR: Unexpected parameter" ; echo "$USAGE" ; } 1>&2
+            exit 1
+            ;;
+    esac
+done
+
+# Script
+CURRENT_BRODER="$(i3h-focused-window | jq -rM '.border')"
 [ "$CURRENT_BRODER" == "normal" ] && i3-msg border none || i3-msg border normal
